name: promote-codefresh
description: >
  Used internally by `promote-build` action for `codefresh` CD.

inputs:

  version:
    description: Version of build to promote.
    required: true

  releases:
    description: Space-delimited list of releases to promote.
    required: true

  env:
    description: Target environment to promote to.
    required: true

  token:
    description: GitHub token to use to check out infra repo.
    required: true
      
runs:
  using: composite
  steps:

    - name: Check out infra repo
      uses: actions/checkout@v3
      with:
        repository: nestoca/infra
        ref: master
        path: infra
        token: ${{ inputs.token }}
        fetch-depth: 0

    - name: Promote
      shell: bash
      run: |-
        docker run --rm \
          --workdir /infra/env/${{ inputs.env }} \
          --env RELEASES="${{ inputs.releases }}" \
          --env DOCKER_TAG="${{ inputs.version }}" \
          --env RELEASE_TEMPLATE="/infra/templates/promote-service/release.yaml.gotmpl" \
          --env VALUES_TEMPLATE="/infra/templates/promote-service/values.yaml.gotmpl" \
          --volume "${{ github.workspace }}/infra:/infra" \
          northamerica-northeast1-docker.pkg.dev/nesto-ci-78a3f2e6/actions/promote-codefresh:0.4.0

    - name: Push changes
      shell: bash
      run: |-
        cd infra
        git config --global user.email "githu@nesto.ca"
        git config --global user.name "nestobot"
        if git diff --quiet; then
          echo "No changes found."
        else
          echo "Pushing changes..."
          git pull
          git add .
          git commit -m 'Promote release(s) "${{ inputs.releases }}" to version ${{ inputs.version }} in ${{ inputs.env }}'
          git push origin master
        fi
