name: publish-people
description: |-
  Publishes pages to Confluence Cloud describing our streams, teams, people and their roles,
  based on `jac` resource files (see: https://github.com/nestoca/jac).

inputs:

  catalog:
    description: Path to `jac` catalog
    required: true

  template:
    description: Path to template file
    required: true

  cc-base-url:
    description: Confluence Cloud base URL
    required: false
    default: https://nestoca.atlassian.net/

  cc-api-token:
    description: Confluence Cloud API token
    required: true

  cc-space-key:
    description: Confluence Cloud space key
    required: false
    default: NP
      
runs:
  using: composite
  steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Build and Run
      shell: bash
      run: |-
        cd ${{ github.action_path }}/go
        go run . render \
          --catalog ${{ inputs.catalog }} \
          --template ${{ inputs.template }} \
          --output teams.html
        go run . publish \
          --base-url ${{ inputs.cc-base-url }} \
          --api-token ${{ inputs.cc-api-token }} \
          --space-key ${{ inputs.cc-space-key }} \
          --page-id 2245001341 \
          --page-title "Streams, teams and people" \
          --page-file teams.html \
          --username mathieu.frenette@nesto.ca
        rm teams.html
