name: build-docker
description: Builds docker image and pushes it to one of nesto's GCP registries (GCR or GAR).

inputs:
  image-name:
    description: Name of image to build and push.
    required: true
      
runs:
  using: composite
  steps:
    - if: ${{ secrets.GCP_KEY != "" }}
      run: echo Key found
      shell: bash
    - if: ${{ secrets.GCP_KEY == "" }}
      run: echo Key not found
      shell: bash
