name: promote-build
description: >
  Promotes build version in given releases of target environment using a certain CD mode.
  Typically called at end of build workflow to auto-promote new build to some environment.

inputs:

  version:
    description: Version of build to promote.
    required: true

  releases:
    description: (Required when promoting via 'codefresh') Space-delimited list of releases to promote (in most cases, will be just the project name).
    required: false

  project:
    description: (Required when promoting via 'joy'); Project whose releases should be promoted.
    required: false

  env:
    description: Target environment to promote to (defaults to `qa`).
    required: false
    default: qa

  via:
    description: >
      Optional promotion path to use, 
      
      - `legacy` -- [Not implemented] using `*-infrastucture` repos and Cloud Build 
      - `codefresh` -- using `infra` monorepo, Codefresh and helmfile, the default)
      - `joy` -- using `catalog` monorepo and deployed with ArgoCD
      
    required: false
    default: codefresh

  token:
    description: GitHub token to use to check out infra repo.
    required: true
      
runs:
  using: composite
  steps:

    - if: inputs.via == 'codefresh'
      uses: nestoca/actions/promote-build/promote-codefresh@v1
      with:
        version: ${{ inputs.version }}
        releases: ${{ inputs.releases }}
        env: ${{ inputs.env }}
        token: ${{ inputs.token }}

    - if: inputs.via == 'joy'
      uses: nestoca/actions/promote-build/promote-joy@devops-1714/deploy-with-joy
      with:
        version: ${{ inputs.version }}
        project: ${{ inputs.project }}
        env: ${{ inputs.env }}
        token: ${{ inputs.token }}

    - if: inputs.via != 'codefresh' || inputs.via != 'joy'
      shell: bash
      run: |
        echo "Error: The only currently supported value for `via` is either `codefresh` or `joy`."
        exit 1
