name: Build image used in get-build-info action

on:
  push:
    branches:
      - master
    paths:
      - "get-build-info/docker/**"

concurrency:
  group: get-build-info

jobs:
  build:
    name: Build get-build-info image
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      id-token: "write"
    steps:

      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get build info
        id: info
        uses: nestoca/actions/get-build-info@v1
        with:
          project: get-build-info
          git-tag-prefix: get-build-info/v

      - name: Build image
        uses: nestoca/actions/build-image@v1
        with:
          name: ${{ steps.info.outputs.project }}
          tags: ${{ steps.info.outputs.docker-tag }},latest
          key: ${{ secrets.GCP_DOCKER_PUBLIC_SA_KEY }}
          repository: actions
          context: get-build-info/docker
          push: "true"

      - name: Tag commit
        uses: silphid/actions/tag-commit@v1
        with:
          tag: ${{ steps.info.outputs.git-tag }}

      - name: Set git identity
        run: |-
            git config --global user.email "github@nesto.ca"
            git config --global user.name "nestobot"

      - name: Promote image in action
        id: promote
        uses: silphid/actions/replace-in-repo@v1
        with:
          glob: get-build-info/action.yaml
          search: |-
            (?<=^\s*image: docker://.+/actions/get-build-info:).+$
          replace: |-
            ${{ steps.info.outputs.docker-tag }}
          message: |-
            Promote image in get-build-info action to ${{ steps.info.outputs.docker-tag }}
