name: Build promote-codefresh image
on:
  push:
    branches:
      - master
    paths:
      - "promote-build/promote-codefresh-docker/**"
concurrency:
  group: get-build-info
jobs:
  build:
    name: Build promote-codefresh image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Get build info
        id: info
        uses: nestoca/actions/get-build-info@v1
        with:
          working-directory: promote-build/promote-codefresh-docker
          project: promote-codefresh
          git-tag-prefix: promote-codefresh/v
      - name: Build image
        uses: nestoca/actions/build-image@v1
        with:
          name: ${{ steps.info.outputs.project }}
          tags: ${{ steps.info.outputs.docker-tag }},latest
          key: ${{ secrets.GCP_KEY }}
          target: actions
          context: promote-build/promote-codefresh-docker
      - name: Tag commit
        uses: silphid/actions/tag-commit@v1
        with:
          tag: ${{ steps.info.outputs.git-tag }}
      - name: Set git identity
        run: |-
            git config --global user.email "nestobot@nesto.ca"
            git config --global user.name "nestobot"
      - name: Promote image in action
        id: promote
        uses: silphid/actions/replace-in-repo@v1
        with:
          message: |-
            Promote image in promote-build action to ${{ steps.info.outputs.docker-tag }}
          glob: promote-build/action.yaml
          search: |-
            (?<=^\s*image: docker://.+/actions/promote-codefresh:).+$
          replace: |-
            ${{ steps.info.outputs.docker-tag }}
