name: Build docker image for get-build-info action
on:
  push:
    branches:
      - master
    paths:
      - "get-build-info/docker/**"
concurrency:
  group: get-build-info
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Get build info
        id: info
        uses: nestoca/actions/get-build-info@v1
        with:
          working-directory: get-build-info/docker
          project: get-build-info
          git-tag-prefix: get-build-info/docker/v
      - name: Build image
        uses: nestoca/actions/build-image@v1
        with:
          name: get-build-info
          tags: ${{ steps.info.outputs.docker-tag }},latest
          key: ${{ secrets.GCP_KEY }}
          target: actions
          context: get-build-info/docker
      - name: Tag commit
        uses: silphid/actions/tag-commit@v1
        with:
          tag: ${{ steps.info.outputs.git-tag }}
      - name: Set git identity
        run: |-
            git config --global user.email "nestobot@nesto.ca"
            git config --global user.name "nestobot"
      - name: Promote image in action
        id: promote
        uses: silphid/actions/replace-in-repo@v1
        with:
          message: |-
            Promote image in get-build-info action to ${{ steps.info.outputs.docker-tag }}
          glob: get-build-info/action.yaml
          search: |-
            (?<=^\s*image: docker://northamerica-northeast1-docker\.pkg\.dev/nesto-ci-78a3f2e6/actions/get-build-info:).+$
          replace: |-
            ${{ steps.info.outputs.docker-tag }}

